import Head from "next/head";
import NavBar from "../components/NavBar";
import Main from "../components/Main";
import About from "../components/About";
import Skills from "../components/Skills";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Karim | Software Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="shortcut icon" href="/assets/favicon.ico" />\
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/asssets/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/asssets/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/asssets/favicon-16x16.png"
        />
      </Head>
      <NavBar />
      <Main />
      <About />
      <Skills />
    </div>
  );
}
